### ISSUE TITLE
bundle external-helpers

### ISSUE THREAD

**Issue by lookfirst** [swimlane-contrib/systemjs-route-bundler#27]
I'm seeing external-helpers get loaded. There should be an easy way to also bundle this.

**Comment by lookfirst** [comment]
WANT

**Comment by amcdnl** [comment]
Look at the systemjs-seed project how we implemented this in gulp.

**Comment by brettstack** [comment]
Could you point me to the line in the gulpfile where you're doing this? It would be nice if this were handled automatically though.

**Comment by amcdnl** [comment]
Ya, its really depends on your setup though.  Wanted to keep it flexible.  https://github.com/Swimlane/angular-systemjs-seed/blob/master/gulpfile.js#L161

**Comment by brettstack** [comment]
I am concatenating es6-module-loader.js, system.js, and system.config.js into system.js, but keeping app.js separate. I just did a search and found you are doing `import 'babel/external-helpers';` in your app.js. Bundling via jspm.bundle handled it automatically which is why I didn't have it. Adding that line breaks the bundle step though... Any ideas? This is the only output:

```
tracing source files...
         tracing app/app.js
```
